### ISSUE TITLE
Ignore non-gleam files

### ISSUE THREAD

**Issue by JScearcy** [giacomocavalieri/birdie#8]
After adding non-gleam files to a projects' tests folder, if one of the snapshots change and I do `gleam run -m birdie` then the process will fail once it gets to those non-gleam files.
I think it's because all files in a test directory are processed with `glance` if I'm not mistaken ([here](https://github.com/giacomocavalieri/birdie/blob/main/src/birdie/internal/titles.gleam#L133-L137)).

Is this by design or would filtering the files in order to check only `*.gleam` be acceptable?

**Comment by giacomocavalieri** [comment]
That's totally a bug! THANKS for pointing ring it out, I'll release a fix today

**Comment by giacomocavalieri** [comment]
Version 1.1.4 fixes this, thank you again!
