### ISSUE TITLE
Potential bug regarding: "All your test should be compiling for Birdie to work!"

### ISSUE THREAD

**Issue by mooreryan** [giacomocavalieri/birdie#9]
I'm getting this with birdie snapshot testing:

```
❌ The test file "./test/qcheck/gen_int_test.gleam"
 is not compiling.
All your test should be compiling for Birdie to work!
```

The project compiles fine with gleam check and gleam test, just not with the gleam run -m birdie.

Some relevant versions:

```
gleam 1.1.0
name = "birdie", version = "1.1.4"
name = "glance", version = "0.11.0"
```

I have also tried the gleam update , then gleam clean, then tried the tests again, but it didn't fix the problem.

---

I found a small reproducible example. If this code is in a test file:

```
pub fn x__test() {
  let x = case Error(-1) {
    // If you change this case to Error(2) it works.
    Error(-2) -> Error("This branch breaks stuff")
    _ -> Ok(0)
  }

  should.equal(x, Ok(0))
}
```

For some reason the negative int in the `Error` in a case statement breaks things.  If you switch it to `Error(2)` it works okay. Also, you can have `Error(-2)` in any other location in the case thing, but just not negative numbers on the thing that is being matched.

**Comment by giacomocavalieri** [comment]
Hello! Thanks for reporting this!! It's a bug in glance, I'll try and contribute a fix, anyways I'll make sure birdie can gracefully handle any of these kind of problems in the next release
